### PR TITLE
Add support for rotation and FT5436 and FT6234

### PR DESCRIPTION
**Pull request by Dzarda7**
Hello @DustinWatts . I finally got some time to create this PR. Both chips were tested. Thank you.

### CODE REVIEW

**Comment by marcelstoer** [comment]
@Dzarda7 Great, thank you so much! Could you maybe incorporate the feedback from https://github.com/DustinWatts/FT6236/pull/9 into this MR?

**Comment by Dzarda7** [comment]
> @Dzarda7 Great, thank you so much! Could you maybe incorporate the feedback from [DustinWatts/FT6236#9](https://github.com/DustinWatts/FT6236/pull/9) into this MR?

I thought I did. Or you mean default resolution values?

**Comment by marcelstoer** [comment]
Default values is fine for me. I think I referred to the consistent logical ordering of the supported chips in all documents and library.json/library.properties we had in the other PR.

**Comment by Dzarda7** [comment]
> Default values is fine for me. I think I referred to the consistent logical ordering of the supported chips in all documents and library.json/library.properties we had in the other PR.

Yes, you are right. I will take a look at it. Thank you for your help.

**Comment by DustinWatts** [comment]
Very nice! Just merged it. Don't know if everything is as you wanted it now, but you can always just create another PR for small changes. :) Thanks! 👍

**Comment by DustinWatts** [comment]
Stupid me... forgot to actually merge.... haha

**Comment by Dzarda7** [comment]
Thanks both of you guys. @DustinWatts can I expect to see this library in PlatformIO and ArduinoIDE at any time? Would be awesome.

**Comment by DustinWatts** [comment]
If I figure out how to do that and they accept it, yes. That would be great. I'll look in to it 😄

**Pull request merged**
